crudapp/crudapp/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crudoperations.urls')),
]

crudapp/crudoperations/urls.py
from django.contrib import admin
from django.urls import path
from crudoperations import views


#from .views import api_response,json_response,add_data

# urlpatterns = [
#     path('getdata', api_response),
#     path('getjson', json_response),
#     path('add', add_data),

# ]

urlpatterns = [
    path('studs', views.studs),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.delete),  
]

crudapp/crudoperations/models.py
from django.db import models

# Create your models here.
class Students(models.Model):
    id = models.AutoField(primary_key=True) 
    name = models.CharField(max_length=250, blank = False, name = "name") 
    email = models.EmailField(max_length=250, blank=False, name = "email")
    marks = models.CharField(max_length=250, blank=False, name = "marks")

crudapp/crudoperations/forms.py
from django import forms  
from crudoperations.models import Students  
class StudentForm(forms.ModelForm):  
    class Meta:  
        model = Students  
        fields = "__all__"  

crudapp/crudoperations/views.py
from traceback import print_exception, print_tb
from django.shortcuts import( render, redirect, get_object_or_404,HttpResponseRedirect)
# from rest_framework.response import Response
from crudoperations.forms import StudentForm  
from django.http import HttpResponse, JsonResponse
from crudoperations.models import Students


# Create your views here.
# def api_response(request):
#     print("rest-ap")
#     context ={"header":"Welcome Knight"}
#     return render (request, "home.html", context)

# def json_response(request):
#     success = "API Hit Sucessfully"
#     return JsonResponse({"status":success})

# @csrf_exempt
# def add_data(request):
#     student = Students()
#     name = request.POST.get('name')
#     email = request.POST.get('email')
#     marks = request.POST.get('marks')
#     student.name = name
#     student.email = email
#     student.marks = marks
#     student.save()
#     return JsonResponse({"status":"success"})

def studs(request):  
    if request.method == "POST":  

        form = StudentForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = StudentForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    students = Students.objects.all()  
    return render(request,"show.html",{'students':students})  
def edit(request, id):  
    student = Students.objects.get(id=id)  
    return render(request,'edit.html', {'student':student})  

# def update(request, id):  
#     student = Students.objects.all(id=id)  
#     form = StudentForm(request.POST, instance = student)  
#     if form.is_valid():  
#         form.save()  
#         return redirect("/show")  
#     return render(request, 'edit.html', {'student': student})   

def update(request, id): 
    if request.method=="POST":
        print("Function is working") 
        name = request.POST.get('name')
        email = request.POST.get('email')
        marks = request.POST.get('marks')

        students=Students(id=id,name=name,email=email,marks=marks)

        students.save()
        return redirect("/show")  



def delete(request,id):  
    student = Students.objects.get(id=id)  
    student.delete()  
    return redirect("/show")  

crudapp/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{ student.id }}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="id" id="id_id" required maxlength="20" value="{{ student.id }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label"> Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="name" id="id_name" required maxlength="100" value="{{ student.name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label"> Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="email" id="id_email" required maxlength="254" value="{{ student.email }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label"> Marks:</label>  
    <div class="col-sm-4">  
        <input type="text" name="marks" id="id_marks" required maxlength="15" value="{{ student.marks }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

crudapp/templates/home.html
<html lang="en">
<head>
    {% load static %}

	<meta charset="utf-8" />
	<title>Table Style</title>
	<meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">



</head>

<body>
<div class="table-title">
<h3>{{header}}</h3> 
</div>
<table class="table-fill">
<thead>
<tr>
<th class="text-left">Month</th>
<th class="text-left">Sales</th>
</tr>
</thead>
<tbody class="table-hover">
<tr>
<td class="text-left">January</td>
<td class="text-left">$ 50,000.00</td>
</tr>
<tr>
<td class="text-left">February</td>
<td class="text-left">$ 10,000.00</td>
</tr>
<tr>
<td class="text-left">March</td>
<td class="text-left">$ 85,000.00</td>
</tr>
<tr>
<td class="text-left">April</td>
<td class="text-left">$ 56,000.00</td>
</tr>
<tr>
<td class="text-left">May</td>
<td class="text-left">$ 98,000.00</td>
</tr>
</tbody>
</table>
  

  </body>

crudapp/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>  
<body>  
<form method="POST" class="post-form" action="/studs">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Id:</label>  
    <div class="col-sm-4">  
      {{ form.id }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Students Name:</label>  
    <div class="col-sm-4">  
      {{ form.name }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Students Email:</label>  
    <div class="col-sm-4">  
      {{ form.email }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Students Marks:</label>  
    <div class="col-sm-4">  
      {{ form.marks }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  

</body>  
</html>  

crudapp/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Students Records</title>  
     {% load static %}  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<style> 
#grad {
  background-image: linear-gradient(rgb(223, 111, 111), rgb(181, 228, 216), blue);
}
</style>
</head>  
<body>  
    <div class="grad">
    

<table class="table table-hover table-borderless table-sm">  
    <thead class="table-primary">
        <tr>  
        <th>Students ID</th>  
        <th> Name</th>  
        <th> Email</th>  
        <th> Marks</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for student in students %}  
    <tr>  
        <td>{{ student.id }}</td>  
        <td>{{ student.name }}</td>  
        <td>{{ student.email }}</td>  
        <td>{{ student.marks }}</td>  
        <td>  
            <a class="btn btn-outline-warning" href="/edit/{{student.id}}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a class="btn btn-outline-danger" href="/delete/{{student.id}}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
    <center><a href="/studs" class="btn btn-primary">Add New Record</a></center>  
</div>
</body>  
</html>  